version: '3'

services:
  payload_mongo:
    container_name: payload_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
