version: '3'

services:

  payload_mongo:
    container_name: payload_mongo
#    image: mongo:latest
    image: mongo:4.4.6
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    networks:
      - payload

volumes:
  data:

networks:
  payload:
