/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'api-users': ApiUserAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    events: Event;
    circles: Circle;
    organisations: Organisation;
    media: Media;
    news: News;
    pages: Page;
    'contact-forms': ContactForm;
    'not-found-pages': NotFoundPage;
    'api-users': ApiUser;
    redirects: Redirect;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    events: EventsSelect<false> | EventsSelect<true>;
    circles: CirclesSelect<false> | CirclesSelect<true>;
    organisations: OrganisationsSelect<false> | OrganisationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'contact-forms': ContactFormsSelect<false> | ContactFormsSelect<true>;
    'not-found-pages': NotFoundPagesSelect<false> | NotFoundPagesSelect<true>;
    'api-users': ApiUsersSelect<false> | ApiUsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'start-page': StartPage;
    'about-bside': AboutBside;
    'event-page': EventPage;
    'event-archive': EventArchive;
    banner: Banner;
  };
  globalsSelect: {
    'start-page': StartPageSelect<false> | StartPageSelect<true>;
    'about-bside': AboutBsideSelect<false> | AboutBsideSelect<true>;
    'event-page': EventPageSelect<false> | EventPageSelect<true>;
    'event-archive': EventArchiveSelect<false> | EventArchiveSelect<true>;
    banner: BannerSelect<false> | BannerSelect<true>;
  };
  locale: 'de' | 'en';
  user:
    | (ApiUser & {
        collection: 'api-users';
      })
    | (User & {
        collection: 'users';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface ApiUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  richText: {
    [k: string]: unknown;
  }[];
  /**
   * Empfohlen: webp mit 1080x1080px
   */
  eventImage?: (string | null) | Media;
  eventLocation: string;
  eventDate: string;
  eventStart: string;
  eventEnd?: string | null;
  /**
   * Der angegebene Kreis wird auf der Veranstaltungsseite angezeigt. Außerdem erscheint die Veranstaltung in der Veranstaltungsübersicht des Kreises und der dazugehörigen Körperschaft.
   */
  eventOwner?:
    | (
        | {
            relationTo: 'organisations';
            value: string | Organisation;
          }
        | {
            relationTo: 'circles';
            value: string | Circle;
          }
      )[]
    | null;
  /**
   * Dieses Feld wird nur benötigt, falls kein eindeutiger Kreis/Körperschaft für die Veranstaltung verantwortlich ist.
   */
  eventOrganizer?: string | null;
  /**
   * Dieser Text wird auf der Detail-Seite über dem Ort angezeigt. Beispiel: VVK 5€ // AK 10€.
   */
  eventExtra?: string | null;
  /**
   * Dieses Feld wird zum Filtern der Veranstaltungen verwendet.
   */
  category?:
    | (
        | 'concert'
        | 'movie'
        | 'theater'
        | 'plenum'
        | 'workshop'
        | 'party'
        | 'exhibition'
        | 'reading'
        | 'lecture'
        | 'other'
      )[]
    | null;
  displayOnHome?: boolean | null;
  displayOnOverview?: boolean | null;
  displayOnOrganisation?: boolean | null;
  displayOnCircle?: boolean | null;
  slug?: string | null;
  /**
   * Dieses Feld wird automatisch verwaltet.
   */
  identifier?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Uploads are currently set to read-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Gib "-" ein, falls es sich um ein rein dekoratives Element handelt
   */
  alt: string;
  blurhash?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    event?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations".
 */
export interface Organisation {
  id: string;
  name: string;
  shortName: string;
  layout?:
    | (
        | {
            title: string;
            /**
             * Optional: Der Teaser wird als kleiner Text oberhalb der Überschrift angezeigt.
             */
            teaser?: string | null;
            /**
             * Achtung: Es darf maximal eine Überschrift der Größe H1 geben!
             */
            level: 'h1' | 'h2' | 'h3' | 'h4';
            /**
             * Dies ist die Größe, die im Browser angezeigt wird.
             */
            as: 'h1' | 'h2' | 'h3' | 'h4';
            backgroundColor: 'white' | 'black';
            /**
             * Optional: Kann zur direkten Verlinkung verwendet werden.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headlineBlock';
          }
        | {
            backgroundColor: 'white' | 'black';
            backgroundWidth: 'full' | 'block';
            columns: {
              /**
               *
               *                             Nur bei erster Spalte in jeweiligem Layout-Element relevant. Bei "Ganze Breite" ist nur eine Spalte
               *                             im Element zulässig. Bei "Halbe Seite" und "Zwei Drittel" müssen es zwei, bei "Ein Drittel"
               *                             drei Spalten sein.
               *
               */
              width: 'full' | 'half' | 'oneThird' | 'twoThirds';
              richText: {
                [k: string]: unknown;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            /**
             * ToDo: Beschreibungstext einfügen.
             */
            media: string | Media;
            size: 'normal' | 'wide' | 'event';
            effects?: ('blur' | 'grayscale' | 'desaturated' | 'darker')[] | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            alignment: 'contentOnLeft' | 'contentOnRight' | 'contentOnBottom';
            backgroundColor: 'white' | 'black';
            headline?: string | null;
            /**
             * ToDo: Beschreibung einfügen.
             */
            media: string | Media;
            effects?: ('blur' | 'grayscale' | 'desaturated' | 'darker')[] | null;
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaContent';
          }
        | {
            title?: string | null;
            text: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            headlineTitle: string;
            /**
             * Optional: Der Teaser wird als kleiner Text oberhalb der Überschrift angezeigt.
             */
            headlineTeaser?: string | null;
            /**
             * Wird dieser Haken gesetzt, wird das Bild auf der linken Seite angezeigt
             */
            reversed?: boolean | null;
            linkText: string;
            linkHref: string;
            /**
             * ToDo: Beschreibung einfügen.
             */
            image: string | Media;
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'teaser';
          }
        | {
            title: string;
            eventSide: 'textLeft' | 'textRight';
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventOverview';
          }
        | {
            title: string;
            circleSide: 'textLeft' | 'textRight';
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'circleOverview';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  hiddenType?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circles".
 */
export interface Circle {
  id: string;
  name: string;
  hiddenType?: string | null;
  organisation: string | Organisation;
  /**
   * Diese Beschreibung wird in den Kreisübersichten in der zweiten Zeile angezeigt.
   */
  description?: string | null;
  /**
   * Empfohlen: webp mit 1280x720px
   */
  circleImage?: (string | null) | Media;
  /**
   * Name eines auf dem Server liegenden Strichmännchen-Bildes
   */
  fallbackImage: string;
  layout?:
    | (
        | {
            title: string;
            /**
             * Optional: Der Teaser wird als kleiner Text oberhalb der Überschrift angezeigt.
             */
            teaser?: string | null;
            /**
             * Achtung: Es darf maximal eine Überschrift der Größe H1 geben!
             */
            level: 'h1' | 'h2' | 'h3' | 'h4';
            /**
             * Dies ist die Größe, die im Browser angezeigt wird.
             */
            as: 'h1' | 'h2' | 'h3' | 'h4';
            backgroundColor: 'white' | 'black';
            /**
             * Optional: Kann zur direkten Verlinkung verwendet werden.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headlineBlock';
          }
        | {
            backgroundColor: 'white' | 'black';
            backgroundWidth: 'full' | 'block';
            columns: {
              /**
               *
               *                             Nur bei erster Spalte in jeweiligem Layout-Element relevant. Bei "Ganze Breite" ist nur eine Spalte
               *                             im Element zulässig. Bei "Halbe Seite" und "Zwei Drittel" müssen es zwei, bei "Ein Drittel"
               *                             drei Spalten sein.
               *
               */
              width: 'full' | 'half' | 'oneThird' | 'twoThirds';
              richText: {
                [k: string]: unknown;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            /**
             * ToDo: Beschreibungstext einfügen.
             */
            media: string | Media;
            size: 'normal' | 'wide' | 'event';
            effects?: ('blur' | 'grayscale' | 'desaturated' | 'darker')[] | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            alignment: 'contentOnLeft' | 'contentOnRight' | 'contentOnBottom';
            backgroundColor: 'white' | 'black';
            headline?: string | null;
            /**
             * ToDo: Beschreibung einfügen.
             */
            media: string | Media;
            effects?: ('blur' | 'grayscale' | 'desaturated' | 'darker')[] | null;
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaContent';
          }
        | {
            headlineTitle: string;
            /**
             * Optional: Der Teaser wird als kleiner Text oberhalb der Überschrift angezeigt.
             */
            headlineTeaser?: string | null;
            /**
             * Wird dieser Haken gesetzt, wird das Bild auf der linken Seite angezeigt
             */
            reversed?: boolean | null;
            linkText: string;
            linkHref: string;
            /**
             * ToDo: Beschreibung einfügen.
             */
            image: string | Media;
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'teaser';
          }
        | {
            title?: string | null;
            text: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            title: string;
            eventSide: 'textLeft' | 'textRight';
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventOverview';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  newsDate: string;
  slug?: string | null;
  newsAuthor?:
    | (
        | {
            relationTo: 'organisations';
            value: string | Organisation;
          }
        | {
            relationTo: 'circles';
            value: string | Circle;
          }
      )[]
    | null;
  newsCategory: 'news' | 'announcements';
  /**
   * Quadratisches Bild!
   */
  newsImage?: (string | null) | Media;
  /**
   * Dieser Text wird auf der Übersichtsseite angezeigt. Maximal 450 Zeichen.
   */
  excerpt: string;
  layout?:
    | (
        | {
            title: string;
            /**
             * Optional: Der Teaser wird als kleiner Text oberhalb der Überschrift angezeigt.
             */
            teaser?: string | null;
            /**
             * Achtung: Es darf maximal eine Überschrift der Größe H1 geben!
             */
            level: 'h1' | 'h2' | 'h3' | 'h4';
            /**
             * Dies ist die Größe, die im Browser angezeigt wird.
             */
            as: 'h1' | 'h2' | 'h3' | 'h4';
            backgroundColor: 'white' | 'black';
            /**
             * Optional: Kann zur direkten Verlinkung verwendet werden.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headlineBlock';
          }
        | {
            backgroundColor: 'white' | 'black';
            backgroundWidth: 'full' | 'block';
            columns: {
              /**
               *
               *                             Nur bei erster Spalte in jeweiligem Layout-Element relevant. Bei "Ganze Breite" ist nur eine Spalte
               *                             im Element zulässig. Bei "Halbe Seite" und "Zwei Drittel" müssen es zwei, bei "Ein Drittel"
               *                             drei Spalten sein.
               *
               */
              width: 'full' | 'half' | 'oneThird' | 'twoThirds';
              richText: {
                [k: string]: unknown;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            /**
             * ToDo: Beschreibungstext einfügen.
             */
            media: string | Media;
            size: 'normal' | 'wide' | 'event';
            effects?: ('blur' | 'grayscale' | 'desaturated' | 'darker')[] | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            alignment: 'contentOnLeft' | 'contentOnRight' | 'contentOnBottom';
            backgroundColor: 'white' | 'black';
            headline?: string | null;
            /**
             * ToDo: Beschreibung einfügen.
             */
            media: string | Media;
            effects?: ('blur' | 'grayscale' | 'desaturated' | 'darker')[] | null;
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaContent';
          }
        | {
            title?: string | null;
            text: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            headlineTitle: string;
            /**
             * Optional: Der Teaser wird als kleiner Text oberhalb der Überschrift angezeigt.
             */
            headlineTeaser?: string | null;
            /**
             * Wird dieser Haken gesetzt, wird das Bild auf der linken Seite angezeigt
             */
            reversed?: boolean | null;
            linkText: string;
            linkHref: string;
            /**
             * ToDo: Beschreibung einfügen.
             */
            image: string | Media;
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'teaser';
          }
        | {
            title: string;
            eventSide: 'textLeft' | 'textRight';
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventOverview';
          }
        | {
            sliderType: 'imageSlider';
            imageSlides?:
              | {
                  image: string | Media;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
      )[]
    | null;
  /**
   * Dieses Feld wird automatisch verwaltet.
   */
  identifier?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug?: string | null;
  layout?:
    | (
        | {
            title: string;
            /**
             * Optional: Der Teaser wird als kleiner Text oberhalb der Überschrift angezeigt.
             */
            teaser?: string | null;
            /**
             * Achtung: Es darf maximal eine Überschrift der Größe H1 geben!
             */
            level: 'h1' | 'h2' | 'h3' | 'h4';
            /**
             * Dies ist die Größe, die im Browser angezeigt wird.
             */
            as: 'h1' | 'h2' | 'h3' | 'h4';
            backgroundColor: 'white' | 'black';
            /**
             * Optional: Kann zur direkten Verlinkung verwendet werden.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headlineBlock';
          }
        | {
            backgroundColor: 'white' | 'black';
            backgroundWidth: 'full' | 'block';
            columns: {
              /**
               *
               *                             Nur bei erster Spalte in jeweiligem Layout-Element relevant. Bei "Ganze Breite" ist nur eine Spalte
               *                             im Element zulässig. Bei "Halbe Seite" und "Zwei Drittel" müssen es zwei, bei "Ein Drittel"
               *                             drei Spalten sein.
               *
               */
              width: 'full' | 'half' | 'oneThird' | 'twoThirds';
              richText: {
                [k: string]: unknown;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            /**
             * ToDo: Beschreibungstext einfügen.
             */
            media: string | Media;
            size: 'normal' | 'wide' | 'event';
            effects?: ('blur' | 'grayscale' | 'desaturated' | 'darker')[] | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            alignment: 'contentOnLeft' | 'contentOnRight' | 'contentOnBottom';
            backgroundColor: 'white' | 'black';
            headline?: string | null;
            /**
             * ToDo: Beschreibung einfügen.
             */
            media: string | Media;
            effects?: ('blur' | 'grayscale' | 'desaturated' | 'darker')[] | null;
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaContent';
          }
        | {
            title?: string | null;
            text: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            headlineTitle: string;
            /**
             * Optional: Der Teaser wird als kleiner Text oberhalb der Überschrift angezeigt.
             */
            headlineTeaser?: string | null;
            /**
             * Wird dieser Haken gesetzt, wird das Bild auf der linken Seite angezeigt
             */
            reversed?: boolean | null;
            linkText: string;
            linkHref: string;
            /**
             * ToDo: Beschreibung einfügen.
             */
            image: string | Media;
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'teaser';
          }
        | {
            title: string;
            eventSide: 'textLeft' | 'textRight';
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventOverview';
          }
        | {
            sliderType: 'imageSlider';
            imageSlides?:
              | {
                  image: string | Media;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
      )[]
    | null;
  parent?: (string | null) | Page;
  breadcrumbs?:
    | {
        doc?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-forms".
 */
export interface ContactForm {
  id: string;
  fullName: string;
  mailAddress: string;
  message: string;
  sendCopyToSender?: string | null;
  recipient: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "not-found-pages".
 */
export interface NotFoundPage {
  id: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-users".
 */
export interface ApiUser {
  id: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * Änderungen an den Redirects werden erst nach einem Neustart des Frontends sichtbar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  roles: ('public' | 'editor' | 'organisator' | 'admin')[];
  circles?: (string | Circle)[] | null;
  sub?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'circles';
        value: string | Circle;
      } | null)
    | ({
        relationTo: 'organisations';
        value: string | Organisation;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'contact-forms';
        value: string | ContactForm;
      } | null)
    | ({
        relationTo: 'not-found-pages';
        value: string | NotFoundPage;
      } | null)
    | ({
        relationTo: 'api-users';
        value: string | ApiUser;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'api-users';
        value: string | ApiUser;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'api-users';
        value: string | ApiUser;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  richText?: T;
  eventImage?: T;
  eventLocation?: T;
  eventDate?: T;
  eventStart?: T;
  eventEnd?: T;
  eventOwner?: T;
  eventOrganizer?: T;
  eventExtra?: T;
  category?: T;
  displayOnHome?: T;
  displayOnOverview?: T;
  displayOnOrganisation?: T;
  displayOnCircle?: T;
  slug?: T;
  identifier?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circles_select".
 */
export interface CirclesSelect<T extends boolean = true> {
  name?: T;
  hiddenType?: T;
  organisation?: T;
  description?: T;
  circleImage?: T;
  fallbackImage?: T;
  layout?:
    | T
    | {
        headlineBlock?:
          | T
          | {
              title?: T;
              teaser?: T;
              level?: T;
              as?: T;
              backgroundColor?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              backgroundColor?: T;
              backgroundWidth?: T;
              columns?:
                | T
                | {
                    width?: T;
                    richText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              size?: T;
              effects?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        mediaContent?:
          | T
          | {
              alignment?: T;
              backgroundColor?: T;
              headline?: T;
              media?: T;
              effects?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        teaser?:
          | T
          | {
              headlineTitle?: T;
              headlineTeaser?: T;
              reversed?: T;
              linkText?: T;
              linkHref?: T;
              image?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        eventOverview?:
          | T
          | {
              title?: T;
              eventSide?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations_select".
 */
export interface OrganisationsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  layout?:
    | T
    | {
        headlineBlock?:
          | T
          | {
              title?: T;
              teaser?: T;
              level?: T;
              as?: T;
              backgroundColor?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              backgroundColor?: T;
              backgroundWidth?: T;
              columns?:
                | T
                | {
                    width?: T;
                    richText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              size?: T;
              effects?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        mediaContent?:
          | T
          | {
              alignment?: T;
              backgroundColor?: T;
              headline?: T;
              media?: T;
              effects?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        teaser?:
          | T
          | {
              headlineTitle?: T;
              headlineTeaser?: T;
              reversed?: T;
              linkText?: T;
              linkHref?: T;
              image?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        eventOverview?:
          | T
          | {
              title?: T;
              eventSide?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        circleOverview?:
          | T
          | {
              title?: T;
              circleSide?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hiddenType?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurhash?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        event?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  newsDate?: T;
  slug?: T;
  newsAuthor?: T;
  newsCategory?: T;
  newsImage?: T;
  excerpt?: T;
  layout?:
    | T
    | {
        headlineBlock?:
          | T
          | {
              title?: T;
              teaser?: T;
              level?: T;
              as?: T;
              backgroundColor?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              backgroundColor?: T;
              backgroundWidth?: T;
              columns?:
                | T
                | {
                    width?: T;
                    richText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              size?: T;
              effects?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        mediaContent?:
          | T
          | {
              alignment?: T;
              backgroundColor?: T;
              headline?: T;
              media?: T;
              effects?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        teaser?:
          | T
          | {
              headlineTitle?: T;
              headlineTeaser?: T;
              reversed?: T;
              linkText?: T;
              linkHref?: T;
              image?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        eventOverview?:
          | T
          | {
              title?: T;
              eventSide?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        slider?:
          | T
          | {
              sliderType?: T;
              imageSlides?:
                | T
                | {
                    image?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  identifier?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        headlineBlock?:
          | T
          | {
              title?: T;
              teaser?: T;
              level?: T;
              as?: T;
              backgroundColor?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              backgroundColor?: T;
              backgroundWidth?: T;
              columns?:
                | T
                | {
                    width?: T;
                    richText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              size?: T;
              effects?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        mediaContent?:
          | T
          | {
              alignment?: T;
              backgroundColor?: T;
              headline?: T;
              media?: T;
              effects?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        teaser?:
          | T
          | {
              headlineTitle?: T;
              headlineTeaser?: T;
              reversed?: T;
              linkText?: T;
              linkHref?: T;
              image?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        eventOverview?:
          | T
          | {
              title?: T;
              eventSide?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        slider?:
          | T
          | {
              sliderType?: T;
              imageSlides?:
                | T
                | {
                    image?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-forms_select".
 */
export interface ContactFormsSelect<T extends boolean = true> {
  fullName?: T;
  mailAddress?: T;
  message?: T;
  sendCopyToSender?: T;
  recipient?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "not-found-pages_select".
 */
export interface NotFoundPagesSelect<T extends boolean = true> {
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-users_select".
 */
export interface ApiUsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  roles?: T;
  circles?: T;
  sub?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "start-page".
 */
export interface StartPage {
  id: string;
  title: string;
  textBody: string;
  buttonText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-bside".
 */
export interface AboutBside {
  id: string;
  title: string;
  textBody: string;
  firstSection: {
    title: string;
    description: string;
  };
  secondSection: {
    title: string;
    description: string;
  };
  thirdSection: {
    title: string;
    description: string;
  };
  fourthSection: {
    title: string;
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-page".
 */
export interface EventPage {
  id: string;
  title: string;
  layout?:
    | (
        | {
            title: string;
            /**
             * Optional: Der Teaser wird als kleiner Text oberhalb der Überschrift angezeigt.
             */
            teaser?: string | null;
            /**
             * Achtung: Es darf maximal eine Überschrift der Größe H1 geben!
             */
            level: 'h1' | 'h2' | 'h3' | 'h4';
            /**
             * Dies ist die Größe, die im Browser angezeigt wird.
             */
            as: 'h1' | 'h2' | 'h3' | 'h4';
            backgroundColor: 'white' | 'black';
            /**
             * Optional: Kann zur direkten Verlinkung verwendet werden.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headlineBlock';
          }
        | {
            backgroundColor: 'white' | 'black';
            backgroundWidth: 'full' | 'block';
            columns: {
              /**
               *
               *                             Nur bei erster Spalte in jeweiligem Layout-Element relevant. Bei "Ganze Breite" ist nur eine Spalte
               *                             im Element zulässig. Bei "Halbe Seite" und "Zwei Drittel" müssen es zwei, bei "Ein Drittel"
               *                             drei Spalten sein.
               *
               */
              width: 'full' | 'half' | 'oneThird' | 'twoThirds';
              richText: {
                [k: string]: unknown;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            /**
             * ToDo: Beschreibungstext einfügen.
             */
            media: string | Media;
            size: 'normal' | 'wide' | 'event';
            effects?: ('blur' | 'grayscale' | 'desaturated' | 'darker')[] | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            alignment: 'contentOnLeft' | 'contentOnRight' | 'contentOnBottom';
            backgroundColor: 'white' | 'black';
            headline?: string | null;
            /**
             * ToDo: Beschreibung einfügen.
             */
            media: string | Media;
            effects?: ('blur' | 'grayscale' | 'desaturated' | 'darker')[] | null;
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaContent';
          }
        | {
            title?: string | null;
            text: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            headlineTitle: string;
            /**
             * Optional: Der Teaser wird als kleiner Text oberhalb der Überschrift angezeigt.
             */
            headlineTeaser?: string | null;
            /**
             * Wird dieser Haken gesetzt, wird das Bild auf der linken Seite angezeigt
             */
            reversed?: boolean | null;
            linkText: string;
            linkHref: string;
            /**
             * ToDo: Beschreibung einfügen.
             */
            image: string | Media;
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'teaser';
          }
        | {
            title: string;
            eventSide: 'textLeft' | 'textRight';
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventOverview';
          }
        | {
            sliderType: 'imageSlider';
            imageSlides?:
              | {
                  image: string | Media;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-archive".
 */
export interface EventArchive {
  id: string;
  title: string;
  /**
   * Wird über dem Archiv angezeigt. Empfohlen: webp mit 1120x288 px.
   */
  headerImage?: (string | null) | Media;
  layout?:
    | (
        | {
            title: string;
            /**
             * Optional: Der Teaser wird als kleiner Text oberhalb der Überschrift angezeigt.
             */
            teaser?: string | null;
            /**
             * Achtung: Es darf maximal eine Überschrift der Größe H1 geben!
             */
            level: 'h1' | 'h2' | 'h3' | 'h4';
            /**
             * Dies ist die Größe, die im Browser angezeigt wird.
             */
            as: 'h1' | 'h2' | 'h3' | 'h4';
            backgroundColor: 'white' | 'black';
            /**
             * Optional: Kann zur direkten Verlinkung verwendet werden.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headlineBlock';
          }
        | {
            backgroundColor: 'white' | 'black';
            backgroundWidth: 'full' | 'block';
            columns: {
              /**
               *
               *                             Nur bei erster Spalte in jeweiligem Layout-Element relevant. Bei "Ganze Breite" ist nur eine Spalte
               *                             im Element zulässig. Bei "Halbe Seite" und "Zwei Drittel" müssen es zwei, bei "Ein Drittel"
               *                             drei Spalten sein.
               *
               */
              width: 'full' | 'half' | 'oneThird' | 'twoThirds';
              richText: {
                [k: string]: unknown;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            /**
             * ToDo: Beschreibungstext einfügen.
             */
            media: string | Media;
            size: 'normal' | 'wide' | 'event';
            effects?: ('blur' | 'grayscale' | 'desaturated' | 'darker')[] | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            alignment: 'contentOnLeft' | 'contentOnRight' | 'contentOnBottom';
            backgroundColor: 'white' | 'black';
            headline?: string | null;
            /**
             * ToDo: Beschreibung einfügen.
             */
            media: string | Media;
            effects?: ('blur' | 'grayscale' | 'desaturated' | 'darker')[] | null;
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaContent';
          }
        | {
            title?: string | null;
            text: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            headlineTitle: string;
            /**
             * Optional: Der Teaser wird als kleiner Text oberhalb der Überschrift angezeigt.
             */
            headlineTeaser?: string | null;
            /**
             * Wird dieser Haken gesetzt, wird das Bild auf der linken Seite angezeigt
             */
            reversed?: boolean | null;
            linkText: string;
            linkHref: string;
            /**
             * ToDo: Beschreibung einfügen.
             */
            image: string | Media;
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'teaser';
          }
        | {
            title: string;
            eventSide: 'textLeft' | 'textRight';
            richText: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventOverview';
          }
        | {
            sliderType: 'imageSlider';
            imageSlides?:
              | {
                  image: string | Media;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner".
 */
export interface Banner {
  id: string;
  /**
   * Das Banner wird überall angezeigt, wenn diese Checkbox aktiviert ist.
   */
  isActive: boolean;
  /**
   * Für jedes Banner muss diese Nummer um +1 erhöht werden.
   */
  bannerId: number;
  /**
   * Der Text, der innerhab des Banners sichtbar ist.
   */
  bannerText: string;
  /**
   * Der Link, der aufgerufen wird, wenn auf das Banner geklickt wird. Falls leer, ist das Banner nicht klickbar.
   */
  bannerLink?: string | null;
  /**
   * Die Hintergrundfarbe des Banner.
   */
  backgroundColor: string;
  /**
   * Die Textfarbe des Banner.
   */
  textColor: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "start-page_select".
 */
export interface StartPageSelect<T extends boolean = true> {
  title?: T;
  textBody?: T;
  buttonText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-bside_select".
 */
export interface AboutBsideSelect<T extends boolean = true> {
  title?: T;
  textBody?: T;
  firstSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  secondSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  thirdSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  fourthSection?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-page_select".
 */
export interface EventPageSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        headlineBlock?:
          | T
          | {
              title?: T;
              teaser?: T;
              level?: T;
              as?: T;
              backgroundColor?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              backgroundColor?: T;
              backgroundWidth?: T;
              columns?:
                | T
                | {
                    width?: T;
                    richText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              size?: T;
              effects?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        mediaContent?:
          | T
          | {
              alignment?: T;
              backgroundColor?: T;
              headline?: T;
              media?: T;
              effects?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        teaser?:
          | T
          | {
              headlineTitle?: T;
              headlineTeaser?: T;
              reversed?: T;
              linkText?: T;
              linkHref?: T;
              image?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        eventOverview?:
          | T
          | {
              title?: T;
              eventSide?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        slider?:
          | T
          | {
              sliderType?: T;
              imageSlides?:
                | T
                | {
                    image?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-archive_select".
 */
export interface EventArchiveSelect<T extends boolean = true> {
  title?: T;
  headerImage?: T;
  layout?:
    | T
    | {
        headlineBlock?:
          | T
          | {
              title?: T;
              teaser?: T;
              level?: T;
              as?: T;
              backgroundColor?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              backgroundColor?: T;
              backgroundWidth?: T;
              columns?:
                | T
                | {
                    width?: T;
                    richText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              size?: T;
              effects?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        mediaContent?:
          | T
          | {
              alignment?: T;
              backgroundColor?: T;
              headline?: T;
              media?: T;
              effects?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        teaser?:
          | T
          | {
              headlineTitle?: T;
              headlineTeaser?: T;
              reversed?: T;
              linkText?: T;
              linkHref?: T;
              image?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        eventOverview?:
          | T
          | {
              title?: T;
              eventSide?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        slider?:
          | T
          | {
              sliderType?: T;
              imageSlides?:
                | T
                | {
                    image?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner_select".
 */
export interface BannerSelect<T extends boolean = true> {
  isActive?: T;
  bannerId?: T;
  bannerText?: T;
  bannerLink?: T;
  backgroundColor?: T;
  textColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
